version: 2

models:
  - name: stg_emergency_contacts

    columns:
      - name: patient_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_patients')
              field: patient_id
      - name: emergency_contact_bloodtype
        data_tests:
          - accepted_values:
              arguments:
                values: ["A+", "AB+", "B+", "O+", "O-", "AB-", "A-", "B-"]

      - name: emergency_contact_phone_number
        data_tests:
          - not_null

      - name: is_valid_phone_number
        data_tests:
          - accepted_values:
              arguments:
                values: [true, false]
      

  - name: stg_providers

    columns:
      - name: npi
        data_tests:
          - unique
          - not_null

      - name: provider_first_name
        data_tests:
          - not_null

      - name: provider_last_name
        data_tests:
          - not_null

      - name: is_valid_enumeration_date
        data_tests:
          - accepted_values:
              arguments:
                values: [true, false]

      - name: is_valid_join_date
        data_tests:
          - accepted_values:
              arguments:
                values: [true, false]

      - name: provider_sex
        data_tests:
          - accepted_values:
              arguments:
                values: ['Female', 'Male', 'Unknown']
      
      - name: provider_specialty
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Oncology','Neurology','Endocrinology','General Medicine','Gynecology','Pulmonology','Family Medicine','Dermatology','Gastroenterology','Cardiology','Internal Medicine'
              ,'ENT (Ear, Nose, and Throat)','Obstetrics','Orthopedics','Psychiatry','Surgery']

  - name: stg_diagnosis

    columns:
      - name: diagnosis_id
        data_tests:
          - unique
          - not_null


      - name : admission_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_admissions')
              field: admission_id

      - name : provider_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_providers')
              field: provider_id

      - name: patient_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_patients')
              field: patient_id

      - name: sub_domain_key
        data_tests:
          - not_null


      - name: sub_domain_1
        data_tests:
          - not_null 
    
  - name: stg_lab_specimen_types

    columns:
      - name: item_id
        data_tests:
          - unique
          - not_null
      - name: category_type
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [,'Endoscopy','Microbiology','Pathology','Neurophysiology','Lab ','Radiology ']

      - name: category_sub_type
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [' Mammography',' Nuclear Medicine',' Blood Panel',' X-ray',' CT',' MRI',' Ultrasound']


      - name: specialty_1
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [' Pulmonology',' Orthopedics','Cardiology','Dentistry',' Gastroenterology',' Dermatology',' Obstetrics','Oncology','General Practice','Neurology','Psychiatry','Endocrinology','Hematology']

      - name: specialty_2
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [' ENT',' Emergency Trauma','Oral Health','Burn Care',' Emergency Medicine',' Gynecology',' General Surgery','Internal Medicine','Behavioral Health','Metabolism']



      - name: 
  - name: stg_lab_events

    columns:
      - name: lab_event_id
        data_tests:
          - unique
          - not_null

      - name: patient_id
        data_tests:
          - not_null
      
      - name: specimen_id
        data_tests:
          - not_null
      
      - name: item_id
        data_tests:
          - not_null

      - name: result_value
        data_tests:
          - not_null

      - name: abnormal_flag
        data_tests:
          - accepted_values:
              arguments:
                values: ['High', 'Low', 'Normal']

  - name: stg_services
    columns:
      - name: patient_id
        data_tests:
          - not_null
      
      - name: service_id
        data_tests:
          - not_null

  - name: stg_transfers
    columns: 
      - name: transfer_id
        data_tests:
          - not_null
          - unique
      
      - name: patient_id
        data_tests:
          - not_null
      
      - name: from_department
        data_tests:
          - not_null
      
      - name: to_department
        data_tests:
          - not_null

  - name: stg_patients

    columns:
      - name: patient_id
        data_tests:
          - unique
          - not_null
      - name: patient_first_name
        data_tests:
          - not_null
      - name: patient_last_name
        data_tests:
          - not_null
      - name: ssn
        data_tests:
          - not_null
          - unique
      - name: blood_type
        data_tests:
          - accepted_values:
              arguments:
                values: ["A+", "AB+", "B+", "O+", "O-", "AB-", "A-", "B-"]
      - name: marital_status
        data_tests:
          - accepted_values:
              arguments:
                values: ['Married', 'Single', 'Divorced', 'Widowed', 'Unknown']
      
  - name: stg_drugs

    columns:
      - name: drug_id
        data_tests:
          - unique
          - not_null

      - name: brand_name
        data_tests:
          - not_null

  - name: stg_admissions

    columns:
      - name: admission_id
        data_tests:
          - unique
          - not_null

      - name: patient_id
        data_tests:
          - not_null

  - name: stg_prescriptions
    columns:
      - name: prescription_id
        data_tests:
          - not_null
          - unique

      - name: patient_id
        data_tests:
          - not_null

      - name: status
        data_tests:
          - accepted_values:
              arguments:
                values: ['completed', 'Active', 'Discontinued']
